<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $primaryKey = 'id_cliente';
    protected $fillable = ['id_cliente',
'razonsocial_cliente',
'tramite_cliente',
'servicio_cliente',
'cotizacion_cliente',
'updated_at',
'created_at',
'cuit_cliente',
'direccion_cliente',
'calle_cliente',
'numero_cliente',
'piso_cliente',
'oficina_cliente',
'localidad_cliente',
'cp_cliente',
'provincia_cliente',
'telefono_cliente',
'fax_cliente',
'mail_cliente',
'mailsec_cliente',
'productor_cliente',
'onservaciones_cliente',
'actividad_cliente',
'iva_cliente',
'iibb_cliente',
'cargo_cliente',
'c1cargo_cliente',
'c1telefono_cliente',
'c1celular_cliente',
'c1mail_cliente',
'c2cargo_cliente',
'c2telefono_cliente',
'c2celular_cliente',
'c2mail_cliente',
'c3cargo_cliente',
'c3telefono_cliente',
'c3celular_cliente',
'c3mail_cliente',
'inicioact_cliente',
'habilitaciones_cliente',
'circ_cliente',
'seccion_cliente',
'manzana_cliente',
'parcela_cliente',
'zonificacion_cliente',
'uf_cliente',
'platnas_cliente',
'adminnombre_cliente',
'admintipodto_cliente',
'adminnro_cliente',
'admincuit_cliente',
'adminnacimiento_cliente',
'admincargo_cliente',
'apoderadonombre_cliente',
'apoderadodto_cliente',
'apoderadonro_cliente',
'apoderadocuit_cliente',
'apoderadocargo_cliente',
'potencial_cliente',
];
}
